### ISSUE TITLE
Describe what the sensitivity/deadzone variables do

### ISSUE THREAD

**Issue by beamer159** [wookieejedi/FSO-Scripts#1]
I would like to tune the sensitivity/deadzone in the mouse-sct script. Here is the relevant snippet of the script.

```
--deadzone and sensitivity settings, controlled by joystick deadzone and sensitivity in-game

--affects how big the bounding circle is for the mouse to move around in
--higher sensitivity setting means smaller bounding circle
Sensitivity_info_min = 1.5, 
Sensitivity_info_step_size = 0.12,

Sensitivity_override = nil,

--deadzone within bounding circle, is affected by bound circle set by sensitivity
Deadzone_info_min = 0.2,
Deadzone_info_step_size = 0.08,

Deadzone_override = nil,
```

Could you provide more detailed descriptions for what the following variables do:

- Sensitivity_info_min
- Sensitivity_info_step_size
- Sensitivity_override
- Deadzone_info_min
- Deadzone_info_step_size
- Deadzone_override

I tried modifying some of these variables one at a time, and some of them appeared to do similar things e.g. modify the bounding circle. Specifically, I would like to do two things:

1. Decrease the deadzone area
2. Increase the bounding circle

EDIT

It seems like I am not able to eliminate deadzone completely, by setting `Deadzone_info_min` to 0 and adjusting my ingame deadzone setting to the lowest option. This creates an unexpectedly large deadzone. Instead, I can set the `Deadzone_info_min` to a tiny value, like 0.001. This effectively removes deadzone. Just seemed a bit weird to me.

**Comment by wookieejedi** [comment]
The usage of these values is in `SetPixelValues` funciton. Here's a bit of summary:
`Sensitivity_info_min`: how big the smallest bounding circle is to track movement (not in exact pixels, it's a percentage of min or screen width or height)
`Sensitivity_info_step_size`: size of step that sensitivity increases by for each sensitivity level (this value is added to the min value above) (also a percentage)
`Sensitivity_override` an actual pixel size for the radius of the bounding circle. If this is set, then this value is used regardless of sensitivity setting

Dead zone variables are the same but correspond to dead zone. 

Regarding setting the dead zone min to 0, I've updated the code to fix that. If you want a high dead zone and larger bounding circle for movement, I suggest just changing the override values only. For example:
`Deadzone_override = 0` and `Sensitivity_override = 50 --radius of 50 pixels, though you'll want to change this depending on your monitor resolution`

If this is still not super clear I can give more info, too.

**Comment by beamer159** [comment]
Fantastic, thanks for the explanation and code change. I ideal setup is the following:

1. No deadzone
2. Mouse circle that extends to the top/bottom of the screen.

Now, I know to achieve this by setting  `Deadzone_info_min` to 0 and `Sensitivity_info_min` to 1, and then setting ingame sensitivity and deadzone to the lowest setting. Thanks again, as well as maintaining this script. It makes the game much more fun to control.

**Comment by wookieejedi** [comment]
Glad to hear you were able to configure just how you'd like and that it makes the game more fun to control!
